import type { FurnitureDef, EquipmentEffects, PlaceType, CatId } from "./furniture";
import type { TraitId } from "./traits";
import type { ActivityId } from "./activities";

function item(id: string, th: string, cat: CatId, model: string, zones: PlaceType[], cost: number,
  traits: Partial<Record<TraitId, number>>, effects: EquipmentEffects, desc: string,
  activities: ActivityId[] = [], minLevel = 1, accent = "#9caf99", useCapacity = 1,
  footprint: [number, number, number] = [1.18, 0.82, 1.5]): FurnitureDef {
  return {
    id, th, emoji: "", cat, model, zones, place: zones[0] === "wall" || zones[0] === "ceiling" ? "wall" : "floor",
    traits, effects, desc, activities, minLevel, accent, useCapacity, footprint, isNew: true,
    grades: [
      { th: `${th} / Standard`, cost, mult: 1 },
      { th: `${th} / Comfort`, cost: Math.round(cost * 2.6 / 10) * 10, mult: 1.95 },
      { th: `${th} / Signature`, cost: Math.round(cost * 6.5 / 10) * 10, mult: 3.2 },
    ],
  };
}

export const EXTRA_FURNITURE: FurnitureDef[] = [
  item("bunkBed", "เตียงสองชั้นพร้อมบันได", "basic", "bunk", ["floor", "loft"], 1700, { sleep: 4, minimal: 2, comfort: 2 }, { beds: 2, privacy: 1, storage: 1 }, "เพิ่มที่นอนสองคนในช่องเดียว เหมาะกับบ้านระดับ 5", ["sleeping"], 2, "#92b7a5", 2, [1.25, 1.32, 1.8]),
  item("dayBed", "เดย์เบดลิ้นชัก", "comfort", "daybed", ["floor", "loft"], 1150, { sleep: 2, comfort: 3, books: 1 }, { beds: 1, seats: 2, storage: 2, recovery: 2 }, "เป็นทั้งที่นอน มุมนั่งอ่าน และช่องเก็บของ", ["sleeping", "reading", "relaxing"], 1, "#dfb59e", 1, [1.25, 1.25, 0.92]),
  item("wallBed", "เตียงพับเข้าตู้", "basic", "murphy", ["floor", "loft"], 2300, { sleep: 4, minimal: 3, luxury: 1 }, { beds: 1, storage: 3, privacy: 2 }, "นอนสบายและลดความรก แต่ราคาสูงกว่าเตียงปกติ", ["sleeping"], 3, "#bdad8c", 1, [1.22, 1.3, 1.75]),
  item("studyPod", "บูธทำงานส่วนตัว", "hobby", "study-pod", ["floor", "loft"], 1850, { books: 4, quiet: 3, tech: 1 }, { privacy: 3, soundproof: 2, seats: 1, power: 1 }, "ลดแรงกดดันจากรูมเมต ให้พื้นที่สมาธิส่วนตัว", ["reading", "journal", "planDay"], 2, "#93aaa6"),
  item("privacyScreen", "ฉากกั้นหวาย", "basic", "screen", ["floor", "loft"], 620, { quiet: 2, nature: 1, vintage: 1 }, { privacy: 4, soundproof: 1 }, "แก้ความอึดอัดเมื่อมีผู้เช่าหลายคน", [], 1, "#c6ab83", 1, [1.2, 0.3, 1.65]),
  item("acousticCurtain", "ม่านอะคูสติก", "safety", "curtain", ["wall"], 1300, { quiet: 4, sleep: 2, light: -1 }, { soundproof: 5, privacy: 2, climate: 1 }, "ลดเสียงทะเลาะและเสียงจากเครื่องใช้ แต่บังแสง", [], 2, "#acb1c3"),
  item("modularLocker", "ล็อกเกอร์ส่วนตัว", "basic", "locker", ["floor", "loft"], 1100, { safety: 2, clean: 2, minimal: 2 }, { storage: 5, privacy: 2, security: 2 }, "เก็บของแยกคน ลดของรกและความกังวล", ["foldLaundry"], 1, "#92a9a3"),
  item("diningSet", "โต๊ะอาหารสี่ที่นั่ง", "comfort", "dining", ["floor", "terrace"], 1500, { social: 3, cooking: 2, comfort: 1 }, { seats: 4, privacy: -1, upkeep: 3 }, "รองรับกิจกรรมร่วมกันสี่คน ช่วยปัญหาที่นั่งไม่พอ", ["eatSnack", "socializing"], 2, "#cca97e", 4, [1.3, 1.2, 0.85]),
  item("beanbag", "บีนแบ็กทรงหยดน้ำ", "comfort", "beanbag", ["floor", "loft", "nook"], 390, { comfort: 3, gaming: 1, clean: -1 }, { seats: 1, recovery: 2 }, "นั่งพักสบาย ราคาย่อมเยา แต่ดูแลความสะอาดเพิ่ม", ["reading", "relaxing"], 1, "#d3b390", 1, [0.75, 0.72, 0.8]),
  item("shoeBench", "ม้านั่งเก็บรองเท้า", "basic", "shoe-bench", ["nook", "floor", "terrace"], 490, { clean: 3, minimal: 2, comfort: 1 }, { seats: 1, storage: 3, cleaning: 0.2 }, "ใช้มุมหน้าบ้านให้มีประโยชน์และเป็นระเบียบ", ["relaxing"], 1, "#b9a884", 1, [0.68, 0.6, 0.55]),
  item("coffeeCart", "รถเข็นกาแฟ", "comfort", "coffee-cart", ["floor", "terrace"], 1050, { cooking: 2, social: 2, vintage: 1 }, { rent: 12, recovery: 2, power: 2, upkeep: 3 }, "ชงชาและกาแฟ เพิ่มค่าเช่าแต่มีค่าใช้จ่ายประจำ", ["makeTea", "eatSnack"], 1, "#bca184"),
  item("dishWasher", "เครื่องล้างจาน", "comfort", "dishwasher", ["floor"], 1700, { clean: 4, cooking: 2, quiet: -1 }, { cleaning: 1.8, power: 4, upkeep: 4 }, "ช่วยล้างจานทุกวัน แต่กินไฟและมีเสียง", ["washHands"], 2, "#b8c7c6"),
  item("dryerUnit", "เครื่องอบผ้า", "comfort", "dryer", ["floor", "terrace"], 1850, { clean: 3, comfort: 2, quiet: -2 }, { cleaning: 1.1, climate: 1, power: 5, upkeep: 4 }, "ผ้าแห้งไวแม้ฝนตก ต้องคุมโหลดไฟ", ["foldLaundry"], 2, "#d1b79c"),
  item("kitchenSink", "เคาน์เตอร์อ่างล้างจาน", "basic", "sink", ["floor", "terrace"], 680, { cooking: 2, clean: 3 }, { cleaning: 0.7, storage: 1, upkeep: 1 }, "ล้างมือและจัดการความสะอาดแบบไม่กินไฟ", ["washHands", "cleaning"], 1, "#9cae9d"),
  item("ovenRange", "เตาอบเบเกอรี่", "comfort", "oven", ["floor"], 2100, { cooking: 4, luxury: 1, clean: -1 }, { rent: 18, power: 6, upkeep: 4, climate: -1 }, "ทำอาหารได้ดีขึ้น แต่สร้างความร้อนและกินไฟมาก", ["cooking"], 3, "#b5c4b5"),
  item("inductionHob", "เตาแม่เหล็กไฟฟ้า", "comfort", "induction", ["surface"], 720, { cooking: 3, safety: 2, tech: 1 }, { security: 1, power: 3, upkeep: 2 }, "ครัวกะทัดรัดบนชั้นวาง ใช้พื้นที่น้อย", ["cooking"], 1, "#687b7c", 1, [0.5, 0.28, 0.09]),
  item("breadToaster", "เครื่องปิ้งขนมปัง", "comfort", "toaster", ["surface"], 310, { cooking: 2, comfort: 1 }, { recovery: 1, power: 1.5, upkeep: 1 }, "มื้อเช้าง่าย ๆ จากอุปกรณ์ชิ้นเล็ก", ["eatSnack"], 1, "#d5a693", 1, [0.4, 0.24, 0.3]),
  item("electricKettle", "กาน้ำร้อนไฟฟ้า", "comfort", "kettle", ["surface"], 260, { spa: 2, cooking: 1, comfort: 1 }, { recovery: 2, power: 1, upkeep: 1 }, "เปิดกิจกรรมชงชาให้ผู้เช่าในพื้นที่จำกัด", ["makeTea"], 1, "#a1b4a5", 1, [0.28, 0.28, 0.4]),
  item("riceCooker", "หม้อหุงข้าวอัจฉริยะ", "comfort", "rice-cooker", ["surface"], 650, { cooking: 3, tech: 1, comfort: 1 }, { recovery: 2, power: 2, upkeep: 1 }, "ทำอาหารประจำวันได้โดยไม่ใช้ชุดครัวขนาดใหญ่", ["cooking", "eatSnack"], 1, "#e2d4bf", 1, [0.44, 0.28, 0.36]),
  item("waterDispenser", "ตู้น้ำร้อนเย็น", "comfort", "water-dispenser", ["floor", "nook"], 850, { comfort: 2, clean: 2, fitness: 1 }, { recovery: 3, air: 1, power: 1, upkeep: 1 }, "เพิ่มการฟื้นพลังและความสะดวกทุกวัน", ["makeTea", "eatSnack"], 1, "#c7d9d3", 1, [0.52, 0.5, 1.3]),
  item("dehumidifier", "เครื่องลดความชื้น", "green", "dehumidifier", ["floor", "nook"], 1600, { clean: 3, comfort: 2, tech: 1 }, { air: 5, climate: 3, power: 3, upkeep: 2 }, "ดูแลอากาศและอุณหภูมิเมื่อผู้เช่าหนาแน่น", [], 2, "#bccfc8", 1, [0.56, 0.48, 0.94]),
  item("ceilingFan", "พัดลมเพดานไม้", "comfort", "ceiling-fan", ["ceiling"], 1050, { comfort: 3, nature: 1, quiet: -1 }, { climate: 4, air: 2, power: 1 }, "กระจายอากาศโดยไม่กินพื้นที่เดิน", [], 2, "#bb986e"),
  item("radiantHeater", "ฮีตเตอร์แผงบาง", "comfort", "heater", ["wall", "floor"], 950, { comfort: 3, sleep: 2, nature: -1 }, { climate: 4, power: 4, upkeep: 2 }, "อุ่นสบาย แต่ต้องบริหารพลังงานให้พอ", [], 2, "#d6cfc1"),
  item("solarPanel", "แผงโซลาร์เซลล์", "green", "solar", ["terrace"], 2900, { nature: 3, tech: 2, luxury: 1 }, { generation: 7, rent: 8, upkeep: 1 }, "ผลิตไฟลดค่าใช้จ่ายและช่วยแก้ไฟเกินกำลังบ้าน", [], 3, "#557b95", 1, [1.22, 0.78, 1.05]),
  item("homeBattery", "แบตเตอรี่สำรองบ้าน", "safety", "battery", ["floor", "nook"], 3700, { safety: 3, tech: 3 }, { generation: 4, security: 3, upkeep: 4 }, "เพิ่มไฟสำรอง ลดแรงกดดันเมื่อใช้เครื่องใช้หลายชิ้น", [], 4, "#b6c7ba", 1, [0.64, 0.56, 1.2]),
  item("meshRouter", "เราเตอร์ตาข่าย", "hobby", "router", ["surface", "wall"], 880, { tech: 4, gaming: 2, books: 1 }, { privacy: 1, power: 1, rent: 10 }, "อินเทอร์เน็ตทั่วบ้าน ทำงานและเล่นเกมได้สะดวก", ["videoCall"], 1, "#e0d9ce", 2, [0.34, 0.26, 0.36]),
  item("smartHub", "ศูนย์ควบคุมบ้าน", "safety", "smart-hub", ["wall", "surface"], 3400, { tech: 4, safety: 2, comfort: 2 }, { security: 3, generation: 2, climate: 2, power: 1, rent: 16 }, "จัดการเครื่องใช้และลดการใช้ไฟสิ้นเปลือง", [], 4, "#9bafab", 1, [0.45, 0.23, 0.4]),
  item("recordPlayer", "เครื่องเล่นแผ่นเสียง", "hobby", "turntable", ["surface"], 930, { music: 4, vintage: 3, quiet: -2 }, { rent: 9, power: 1, soundproof: -1 }, "เสียงเพลงอบอุ่น แต่ผู้เช่าสายสงบอาจไม่ถูกใจ", ["music"], 2, "#ad8e72", 1, [0.5, 0.3, 0.26]),
  item("arcadeCabinet", "ตู้เกมอาร์เคด", "hobby", "arcade", ["floor"], 2800, { gaming: 4, social: 2, quiet: -3 }, { rent: 24, power: 5, soundproof: -2, upkeep: 4 }, "ค่าเช่าสูงขึ้น แต่เสียงกับไฟฟ้าคือสิ่งแลกเปลี่ยน", ["gaming"], 3, "#b48fa5", 1, [0.88, 0.78, 1.8]),
  item("vrStation", "สถานีแว่น VR", "hobby", "vr", ["floor", "loft"], 3600, { gaming: 4, tech: 4, fitness: 1 }, { power: 4, recovery: 2, upkeep: 5, rent: 22 }, "เปิดโลกเกมแบบใหม่ ต้องเผื่องบดูแลอุปกรณ์", ["gaming", "exercising"], 4, "#8c9daf"),
  item("treadmill", "ลู่วิ่งพับเก็บ", "hobby", "treadmill", ["floor", "terrace"], 2100, { fitness: 4, comfort: 1, quiet: -2 }, { recovery: 4, power: 4, upkeep: 3 }, "ออกกำลังกายได้ทุกวัน แต่มีเสียงและกินไฟ", ["exercising", "briskWalk"], 2, "#7e9692", 1, [1.28, 1.18, 1.3]),
  item("rowingMachine", "เครื่องกรรเชียงบก", "hobby", "rowing", ["floor", "terrace"], 1950, { fitness: 4, nature: 1, minimal: -1 }, { recovery: 4, upkeep: 2 }, "ออกกำลังทั้งตัวโดยไม่ใช้ไฟ", ["exercising"], 2, "#b09b7b", 1, [1.3, 0.76, 0.85]),
  item("punchingBag", "กระสอบทรายตั้งพื้น", "hobby", "punchbag", ["floor", "terrace"], 940, { fitness: 4, quiet: -3 }, { recovery: 3, privacy: -1, soundproof: -2 }, "คลายเครียดแต่กวนรูมเมต ควรวางนอกบ้าน", ["exercising"], 1, "#b78772", 1, [0.67, 0.67, 1.65]),
  item("meditationCushion", "เบาะสมาธิพร้อมแท่น", "green", "meditation", ["floor", "loft", "nook", "terrace"], 340, { quiet: 3, spa: 3, nature: 1 }, { privacy: 2, recovery: 3 }, "มุมพักใจสำหรับบ้านที่มีคนอยู่ร่วมกันหลายคน", ["meditate", "relaxing"], 1, "#baa5b6", 1, [0.67, 0.61, 0.4]),
  item("craftDesk", "โต๊ะงานคราฟต์", "hobby", "craft", ["floor", "loft"], 1500, { art: 4, books: 1, clean: -1 }, { storage: 2, seats: 1, rent: 11, upkeep: 2 }, "มุมสร้างสรรค์พร้อมช่องเก็บอุปกรณ์", ["sketch", "journal"], 2, "#bbad86"),
  item("sewingMachine", "จักรเย็บผ้า", "hobby", "sewing", ["surface"], 1160, { art: 3, vintage: 2, quiet: -1 }, { rent: 15, power: 2, upkeep: 2 }, "ให้ผู้เช่าทำงานฝีมือและเพิ่มมูลค่าห้อง", ["foldLaundry", "sketch"], 2, "#b5d0c5", 1, [0.5, 0.28, 0.46]),
  item("terrariumDome", "สวนขวดโดมแก้ว", "green", "terrarium", ["surface", "nook", "floor"], 460, { nature: 3, art: 2, spa: 1 }, { air: 2, recovery: 1 }, "สวนจิ๋วที่เหมาะกับพื้นที่บนชั้นวาง", ["watering"], 1, "#83aa86", 1, [0.42, 0.3, 0.5]),
  item("hydroponicTower", "เสาปลูกผักไฮโดร", "green", "hydroponic", ["terrace", "floor"], 2350, { nature: 4, cooking: 2, tech: 2 }, { air: 6, rent: 12, power: 2, upkeep: 3 }, "ปลูกผักแนวตั้งและช่วยคุณภาพอากาศ", ["watering"], 3, "#b3c9a1", 1, [0.76, 0.76, 1.75]),
  item("herbPlanter", "กระบะสมุนไพร", "green", "herbs", ["terrace", "surface"], 410, { nature: 3, cooking: 3 }, { air: 3, recovery: 1, upkeep: 1 }, "ปลูกวัตถุดิบเอง ใช้ได้ทั้งสวนและชั้นวาง", ["watering", "cooking"], 1, "#b49c76", 1, [0.5, 0.3, 0.5]),
  item("birdBath", "อ่างน้ำนก", "green", "birdbath", ["terrace"], 640, { nature: 4, pets: 2, clean: -1 }, { air: 2, recovery: 2, upkeep: 2 }, "ชวนนกมาเยือนสวน ต้องดูแลน้ำให้สะอาด", ["birdwatch", "feedPet"], 1, "#b2c3b1", 1, [0.70, 0.7, 0.95]),
  item("zenFountain", "น้ำพุหินเซน", "green", "fountain", ["terrace", "nook", "floor"], 920, { spa: 4, nature: 2, quiet: 1 }, { recovery: 4, privacy: 1, power: 1, upkeep: 2 }, "เสียงน้ำช่วยผ่อนคลายหลังใช้พื้นที่ร่วมกัน", ["relaxing", "meditate"], 2, "#aeb1a0", 1, [0.65, 0.61, 1.10]),
  item("catTree", "คอนโดแมวหลายชั้น", "comfort", "cat-tree", ["floor", "terrace"], 930, { pets: 4, nature: 1, clean: -2 }, { privacy: 1, cleaning: -0.6, upkeep: 2 }, "มีที่ให้น้องปีนเล่น แต่ต้องจัดการขนสัตว์", ["feedPet"], 1, "#c1ad94", 1, [0.85, 0.78, 1.6]),
  item("petFeeder", "เครื่องให้อาหารอัตโนมัติ", "comfort", "feeder", ["nook", "floor"], 860, { pets: 4, tech: 2, clean: 1 }, { cleaning: 0.5, power: 1, upkeep: 2 }, "ให้อาหารเป็นเวลา ลดสิ่งสกปรกและภาระผู้เช่า", ["feedPet"], 2, "#dac7aa", 1, [0.6, 0.58, 0.64]),
  item("litterStation", "ห้องน้ำแมวอัตโนมัติ", "comfort", "litter", ["floor", "terrace"], 2250, { pets: 3, clean: 4, tech: 2 }, { cleaning: 2, air: 2, power: 2, upkeep: 4 }, "แก้ปัญหากลิ่นและความสะอาดเมื่อเลี้ยงสัตว์", ["cleaning"], 3, "#bdcabb", 1, [0.88, 0.84, 0.94]),
  item("firstAidCabinet", "ตู้ปฐมพยาบาล", "safety", "first-aid", ["wall"], 420, { safety: 3, clean: 2 }, { security: 3, recovery: 2, upkeep: 1 }, "อุปกรณ์พื้นฐานสำหรับบ้านแชร์และสายออกกำลัง", [], 1, "#d2ddd0"),
  item("smokeAlarm", "เซนเซอร์ควันอัจฉริยะ", "safety", "smoke-alarm", ["ceiling", "wall"], 560, { safety: 4, tech: 2 }, { security: 5, power: 0.3, upkeep: 1 }, "เพิ่มความปลอดภัย ช่วยลดความเครียดเมื่ออยู่หลายคน", [], 2, "#e2ded2"),
  item("sprinklerHead", "ชุดดับเพลิงเพดาน", "safety", "sprinkler", ["ceiling"], 1900, { safety: 4, luxury: 1 }, { security: 7, upkeep: 3 }, "การป้องกันระดับสูงสำหรับวิลล่าสี่คน", [], 4, "#b7c6c3"),
  item("pendantLight", "โคมแขวนกระจกสี", "deco", "pendant", ["ceiling"], 690, { light: 4, art: 2, luxury: 1 }, { climate: 1, power: 1, rent: 8 }, "เพิ่มมูลค่าบ้านจากแสงอุ่นโดยไม่ใช้พื้นที่พื้น", [], 1, "#d1b386"),
  item("wallSconce", "โคมไฟกิ่งคู่", "deco", "sconce", ["wall"], 570, { light: 3, vintage: 2, books: 1 }, { power: 0.5, rent: 6 }, "แสงอ่านหนังสืออ่อนโยนสำหรับผนังแต่ละมุม", [], 1, "#c8b18b"),
  item("mirrorCabinet", "ตู้กระจกสปา", "deco", "mirror", ["wall"], 1450, { luxury: 3, clean: 2, spa: 2 }, { storage: 3, privacy: 2, recovery: 2, rent: 10 }, "กระจกบานใหญ่พร้อมพื้นที่เก็บของและมุมดูแลตัวเอง", ["brushHair", "brushTeeth"], 3, "#b8bba8"),
];